const projects = [
            {
                id: 1,
                title: "Apprenti IA / Data",
                type: "work",
                company: "ATC",
                startDate: "01/2025",
                endDate: "08/2026",
                description: "Docker-based CI/CD pipeline using GitHub Actions and AWS. Automates testing, building, and deployment processes for multiple environments with monitoring and rollback capabilities.",
                position: ["Développeur","Data Scientist"],
                category: ["Automatisation","Deep Learning"],
                keywords: ["Python", "Excel", "Automatisation", "LLM"],
                tags: ["Python", "Excel", "Automatisation", "LLM"],
                github: null,
                demo: null,
                overview: "A comprehensive CI/CD automation solution that streamlines the development workflow from code commit to production deployment. This system ensures reliable, repeatable deployments while maintaining high code quality and system reliability through automated testing and monitoring.",
                duration: "En cours",
                team: "Solo",
                status: "En cours",
                images: [{ url: "https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=800", caption: "GitHub Actions workflow visualization" }, { url: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=800", caption: "AWS infrastructure monitoring dashboard" }],
                techStack: ["Python", "Excel","Hugging Face"],
                features: ["Automated testing pipeline with unit, integration, and E2E tests", "Multi-stage Docker builds optimized for production", "Infrastructure as Code using Terraform and CloudFormation", "Blue-green deployments with zero-downtime rollouts", "Automated rollback mechanisms on deployment failures", "Real-time monitoring and alerting with Prometheus and Grafana", "Security scanning for containers and dependencies", "Environment-specific configurations and secrets management"],
                challenges: "Setting up reliable blue-green deployments while managing database migrations was complex. I had to ensure that the pipeline could handle both forward and backward compatibility during deployments. Another challenge was implementing comprehensive monitoring that could detect issues before they affected users, requiring careful selection of metrics and alert thresholds.",
                learnings: "This project taught me about infrastructure automation and the importance of treating infrastructure as code. I gained experience with AWS services and learned about deployment strategies that minimize risk. The project also improved my understanding of monitoring and observability practices in production systems."
            },
            {
                id: 2,
                title: "Stage développeur Funnel Marketing Data Driven",
                type: "work",
                company: "PicturifyAI",
                startDate: "06/2024",
                endDate: "09/2024",
                description: "Full-stack e-commerce solution with React frontend, Node.js backend, and PostgreSQL database. Features include user authentication, payment processing, inventory management, and admin dashboard.",
                position: ["Développeur","Web Scraper"],
                category: ["Machine Learning", "Web Scraping / Collecte de données","Automatisation"],
                keywords: ["python", "excel","webscraping","machine learning","automatisation"],
                tags: ["Python", "Excel", "Octoparse","Automatisation"],
                github: "",
                demo: "",
                overview: "This comprehensive e-commerce platform was built to provide a complete online shopping experience. The project demonstrates full-stack development skills with a focus on user experience, security, and scalability. The application handles everything from product browsing to order fulfillment, with a robust admin panel for business management.",
                duration: "3 mois",
                team: "7 personnes",
                status: "Terminé",
                images: [],
                techStack: ["Python", "Excel", "Octoparse","Zapier","Appollo","Akkio"],
                features: ["User authentication with JWT tokens and secure password hashing", "Product catalog with search, filtering, and pagination", "Shopping cart with persistent storage and real-time updates", "Secure payment processing using Stripe integration", "Order management system with status tracking", "Admin dashboard with inventory and user management", "Responsive design for mobile and desktop devices", "Email notifications for order confirmations and updates"],
                challenges: "The main challenges included implementing secure payment processing, managing complex state across the application, and optimizing database queries for large product catalogs. I solved the payment security by implementing proper validation and using Stripe's secure tokenization. For state management, I used Redux with proper middleware, and optimized database performance with indexing and efficient query patterns.",
                learnings: "This project taught me the importance of security in e-commerce applications, especially regarding payment processing and user data protection. I gained deep experience with full-stack architecture, API design, and the complexities of managing financial transactions. The project also improved my skills in database design and optimization."
            },
            {
                id: 3,
                title: "Stage collecte de données de véhicules avec leurs caractéristiques (marque, modèle,image,..)",
                type: "work",
                company: "Consult Trends",
                startDate: "07/2023",
                endDate: "09/2023",
                description: "React Native app for expense tracking with offline support, data visualization, and cloud sync. Features camera integration for receipt scanning and budget alerts.",
                position: "Web Scraper",
                category: ["Web Scraping / Collecte de données"],
                keywords: ["pandas","beautiful soup","jupyter","excel"],
                tags: ["React Native", "SQLite", "Camera", "Charts", "AsyncStorage"],
                github: "",
                demo: null,
                overview: "A comprehensive mobile expense tracking application that helps users manage their finances on the go. The app combines intuitive expense entry with powerful analytics and budgeting features, designed to work seamlessly both online and offline.",
                duration: "2 mois",
                team: "4 personnes",
                status: "Terminé",
                images: [{ url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400", caption: "Expense entry screen with camera integration" }, { url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400", caption: "Analytics dashboard with spending insights" }, { url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400", caption: "Budget tracking and alert system" }],
                techStack: ["Pandas","Beautiful soup","Jupyter","Excel"],
                features: ["Intuitive expense entry with category selection", "Camera integration for receipt capture and storage", "Offline functionality with local SQLite database", "Cloud synchronization when connection is available", "Budget setting and alert notifications", "Detailed analytics with charts and spending insights", "Export functionality for financial reports", "Multi-currency support with exchange rate updates"],
                challenges: "Implementing reliable offline synchronization was the biggest challenge, especially handling conflicts when data changes both locally and on the server. The camera integration also required careful handling of permissions and image optimization. Performance optimization for large datasets on mobile devices needed special attention.",
                learnings: "This project gave me extensive experience with React Native and mobile development patterns. I learned about offline-first application design and data synchronization strategies. The project also taught me about mobile UI/UX principles and the importance of performance optimization on resource-constrained devices."
            },
            {
                id: 5,
                title: "Stage d'analyse de données",
                type: "work",
                company: "Custeed",
                startDate: "05/2022",
                endDate: "07/2022",
                description: "Reusable UI component library built with TypeScript and styled-components. Includes comprehensive documentation, unit tests, and Storybook integration for component development.",
                position: "Data Analyst",
                category: ["Analyse et Visualisation de données","API","Automatisation"],
                keywords: ["analyse de données","github","power bi","python"],
                tags: ["Analyse de données","Github","Power BI","Python"],
                github: "",
                demo: "",
                overview: "A comprehensive React component library designed to accelerate development and ensure design consistency across projects. Built with TypeScript for type safety and styled-components for flexible styling, this library provides a solid foundation for building modern web applications.",
                duration: "3 mois",
                team: "2 personnes",
                status: "Terminé",
                images: [{ url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800", caption: "Storybook interface showing component variations" }, { url: "https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=800", caption: "Component documentation with usage examples" }],
                techStack: ["Github","Power BI","Python"],
                features: ["20+ reusable components with consistent design patterns", "Full TypeScript support with comprehensive type definitions", "Flexible theming system using styled-components", "Interactive documentation with Storybook", "Comprehensive unit tests with high coverage", "Automated testing and deployment pipeline", "NPM package with proper versioning and changelogs", "Accessibility features built into all components"],
                challenges: "Creating a flexible theming system that could accommodate different design requirements while maintaining consistency was complex. I also had to ensure proper tree-shaking and bundle optimization for library consumers. Testing components in isolation while ensuring they work well together required careful planning of the testing strategy.",
                learnings: "This project taught me about library design patterns and the importance of API consistency. I gained deep knowledge of TypeScript's advanced features and learned about package publishing and versioning strategies. The experience also improved my understanding of accessibility principles and how to build inclusive user interfaces."
            },
            {
                id: 5,
                title: "Modèle de prédiction des retours de commande en ligne",
                type: "project",
                company: "ba&sh",
                startDate: "09/2023",
                endDate: "12/2023",
                description: "RESTful API built with Express.js and MongoDB for task management. Includes user authentication, CRUD operations, file uploads, and real-time notifications using WebSockets.",
                position: ["Data Scientist","Data Analyst"],
                category: ["Machine Learning","Analyse et Visualisation de données"],
                keywords: ["Python",'Jupyter notebook','Power BI','Scikit Learn'],
                tags: ["Python",'Jupyter notebook','Power BI'],
                github: "",
                demo: null,
                overview: "A robust RESTful API designed to power task management applications. Built with scalability and performance in mind, this API provides comprehensive task management capabilities with real-time features. The architecture follows REST principles while incorporating modern features like WebSocket connections for live updates.",
                duration: "3 mois",
                team: "4 personnes",
                status: "Terminé",
                images: [{ url: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800", caption: "API documentation and endpoint testing interface" }],
                techStack: ["Python",'Jupyter notebook','Power BI'],
                features: ["RESTful API design with proper HTTP methods and status codes", "User authentication and authorization with JWT tokens", "CRUD operations for tasks, projects, and user management", "File upload functionality for task attachments", "Real-time notifications using WebSocket connections", "Data validation and sanitization for security", "Rate limiting and request throttling", "Comprehensive error handling and logging"],
                challenges: "Implementing real-time features while maintaining API performance was challenging. I had to carefully design the WebSocket integration to avoid conflicts with REST endpoints. Another challenge was handling file uploads securely while managing storage efficiently. I solved these by implementing proper middleware chains and using cloud storage with signed URLs.",
                learnings: "This project deepened my understanding of API design principles and real-time communication patterns. I learned about the trade-offs between different authentication methods and gained experience with MongoDB's aggregation pipeline for complex queries. The project also taught me about API security best practices and performance optimization techniques."
            },
            {
                id: 6,
                title: "Modèle d'adaptive learning pour la personnalisation du parcours d'apprentissage utilisateur",
                type: "project",
                company: "TinyCoaching",
                startDate: "01/2023",
                endDate: "03/2023",
                description: "React-based weather dashboard with geolocation support, favorites system, and 7-day forecasts. Uses OpenWeather API and features responsive design with dark/light themes.",
                position: "Data Scientist",
                category: ["Machine Learning","Analyse et Visualisation de données"],
                keywords: ["Machine Learning", "Analyse et Visualisation de données", "Power BI", "Python", "dashboard"],
                tags: ["Machine Learning", "Analyse et Visualisation de données", "Power BI", "Python", "dashboard"],
                github: "https://github.com/yourusername/weather-dashboard",
                demo: "https://your-weather-app.com",
                overview: "An intuitive weather dashboard that provides comprehensive weather information with a focus on user experience and accessibility. The application combines current weather data with extended forecasts, featuring a clean interface that adapts to different screen sizes and user preferences.",
                duration: "3 mois",
                team: "4 personnes",
                status: "Terminé",
                images: [{ url: "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?w=800", caption: "Main dashboard showing current weather and forecasts" }, { url: "https://images.unsplash.com/photo-1592210454359-9043f067919b?w=800", caption: "Dark theme with detailed weather metrics" }],
                techStack: ["Python","Power BI","Github","Jupyter Notebook"],
                features: ["Automatic location detection using browser geolocation", "Search functionality for cities worldwide", "Current weather conditions with detailed metrics", "7-day weather forecast with hourly breakdowns", "Favorites system for quick access to saved locations", "Dark/light theme toggle with user preference persistence", "Responsive design optimized for all device sizes", "Weather data visualization with interactive charts"],
                challenges: "The biggest challenge was handling the various edge cases with the geolocation API and managing API rate limits efficiently. Weather data can be inconsistent, so I implemented robust error handling and fallback mechanisms. I also had to optimize the app for different network conditions and handle offline scenarios gracefully.",
                learnings: "This project improved my skills in working with external APIs and handling asynchronous data. I learned about browser APIs like Geolocation and gained experience in creating responsive designs that work well across different devices. The project also taught me about state management patterns in React and performance optimization techniques."
            },
            {
                id: 7,
                title: "Modèles d'annotation et de classification d'images pour les vides et les composants dans les circuits imprimés",
                type: "project",
                company: "Projet d'école",
                startDate: "11/2024",
                endDate: "11/2024",
                description: "React-based weather dashboard with geolocation support, favorites system, and 7-day forecasts. Uses OpenWeather API and features responsive design with dark/light themes.",
                position: "Data Scientist",
                category: ["Deep Learning"],
                keywords: ["Deep Learning","Hugging Face"," Flask","Déploiement","Github"],
                tags: ["Deep Learning","Hugging Face"," Flask","Déploiement","Github"],
                github: "https://github.com/IThioye/final_project_sam_yolo",
                demo: "https://ibrahimathioye-sam-yolo-flask.hf.space/",
                overview: "An intuitive weather dashboard that provides comprehensive weather information with a focus on user experience and accessibility. The application combines current weather data with extended forecasts, featuring a clean interface that adapts to different screen sizes and user preferences.",
                duration: "1 mois",
                team: "4 personnes",
                status: "Terminé",
                images: [{ url: "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?w=800", caption: "Main dashboard showing current weather and forecasts" }, { url: "https://images.unsplash.com/photo-1592210454359-9043f067919b?w=800", caption: "Dark theme with detailed weather metrics" }],
                techStack: ["Python","Flask","Github","Hugging Face"],
                features: ["Automatic location detection using browser geolocation", "Search functionality for cities worldwide", "Current weather conditions with detailed metrics", "7-day weather forecast with hourly breakdowns", "Favorites system for quick access to saved locations", "Dark/light theme toggle with user preference persistence", "Responsive design optimized for all device sizes", "Weather data visualization with interactive charts"],
                challenges: "The biggest challenge was handling the various edge cases with the geolocation API and managing API rate limits efficiently. Weather data can be inconsistent, so I implemented robust error handling and fallback mechanisms. I also had to optimize the app for different network conditions and handle offline scenarios gracefully.",
                learnings: "This project improved my skills in working with external APIs and handling asynchronous data. I learned about browser APIs like Geolocation and gained experience in creating responsive designs that work well across different devices. The project also taught me about state management patterns in React and performance optimization techniques."
            }

        ];
        
const certifications = [
            {
                id: 1,
                title: "Microsoft Certified: Azure Data Scientist Associate",
                issuer: "Microsoft",
                date: "2025",
                link: "https://learn.microsoft.com/api/credentials/share/en-us/IbrahimaTHIOYE-2392/321034E6B5AA0D55?sharingId=571CABD87EB452E1"
            },
            {
                id: 2,
                title: "AI Product Engineering: From Concept to Market",
                issuer: "UC Berkeley",
                date: "2025",
                link: "https://badgr.com/public/assertions/kltf95JQQQWVjNzApdzw6w"
            }
        ];

export { projects, certifications };

