const projects = [
            {
                id: 1,
                title: "Apprenti IA / Data",
                type: "work",
                company: "ATC",
                startDate: "01/2025",
                endDate: "08/2026",
                description: "Alternance",
                position: ["Développeur","Data Scientist"],
                category: ["Automatisation","Deep Learning"],
                keywords: ["Python", "Excel", "Automatisation", "LLM"],
                tags: ["Python", "Excel", "Automatisation", "LLM"],
                github: null,
                demo: null,
                overview: "Développement de solutions data & IA visant à automatiser/accélérer les processus métiers.",
                duration: "En cours",
                team: "Solo",
                status: "En cours",
                images: [{ url: "https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=800", caption: "GitHub Actions workflow visualization" }, { url: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=800", caption: "AWS infrastructure monitoring dashboard" }],
                techStack: ["Python", "Excel","Hugging Face"],
                features: ["Développement de solutions de reporting automatisées générant des fichiers Excel et Word (graphiques, tableaux, mise en forme).", "Implémentation d’un système de résumé de documents avec anonymisation via modèles NER et LLM", " Extraction et traitement de données réglementaires pour alimenter un chatbot interne."],
                challenges: "Travailler avec des données sensibles limitent considérablement le champ des possibles quand on travaille dans l'IA. Au lieu de directement créer le prompt pour définir le format du résumé, j'ai dù d'abord créé un système d'anonymisation/déanonymisation des textes sensibles",
                learnings: "J'ai appris à transformer un processus métier manuel en automatisation et j'ai pu apprendre à automatiser la création d'applications python"
            },
            {
                id: 2,
                title: "Stage développeur IA",
                type: "work",
                company: "PicturifyAI",
                startDate: "06/2024",
                endDate: "09/2024",
                description: "Développement d'un funnel marketing de conversion data-driven et alimenté par l'IA",
                position: ["Développeur","Web Scraper"],
                category: ["Machine Learning", "Web Scraping / Collecte de données","Automatisation"],
                keywords: ["python", "excel","webscraping","machine learning","automatisation"],
                tags: ["Python", "Excel", "Octoparse","Automatisation"],
                github: "",
                demo: "",
                overview: "Développement d’un funnel marketing de conversion data-driven et alimenté par l’IA.",
                duration: "3 mois",
                team: "7 personnes",
                status: "Terminé",
                images: [],
                techStack: ["Python", "Excel", "Octoparse","Zapier","Appollo","Akkio"],
                features: ["Collecte et nettoyage de données de leads via Octoparse, Phantombuster, Appolo, Python, Excel.", "Développement et déploiement de modèles de lead scoring et d’analyse de sentiments (Akkio, API).", "Automatisation du funnel via Wix, Apolo et Zapier."],
                challenges: "",
                learnings: "J'ai appris l'importance de se former au no-code quand on travaille avec une équipe non-technique"
            },
            {
                id: 3,
                title: "Stage de webscraping",
                type: "work",
                company: "Consult Trends",
                startDate: "07/2023",
                endDate: "09/2023",
                description: "Collecte de données de véhicules avec leurs caractéristiques (marque, modèle,image,..)",
                position: "Web Scraper",
                category: ["Web Scraping / Collecte de données"],
                keywords: ["pandas","beautiful soup","jupyter","excel"],
                tags: ["Pandas","Beautiful Soup","Webscraping"],
                github: "",
                demo: null,
                overview: "Collecte et aggrégation de données de véhicules (marque,modèle,année,description,images,etc)",
                duration: "2 mois",
                team: "4 personnes",
                status: "Terminé",
                images: [],
                techStack: ["Pandas","Beautiful soup","Jupyter","Excel"],
                features: ["Utilisation de scripts pour automatiser la collecte de données", "organisation des données par marque,modèles dans des dossiers bien nommés"],
                challenges: "Scraper intensément un même site web entraine un blocage côté serveur, il fallait donc prendre en compte dans le script ces blocages pour relancer le code",
                learnings: "J'ai appris à automatiser le scraping d'un site web"
            },
            {
                id: 5,
                title: "Stage d'analyse de données",
                type: "work",
                company: "Custeed",
                startDate: "05/2022",
                endDate: "07/2022",
                description: "Analyse des données internes (commerciaux) et externes (clients)",
                position: "Data Analyst",
                category: ["Analyse et Visualisation de données","API","Automatisation"],
                keywords: ["analyse de données","github","power bi","python"],
                tags: ["Analyse de données","Github","Power BI","Python"],
                github: "",
                demo: "",
                overview: "A comprehensive React component library designed to accelerate development and ensure design consistency across projects. Built with TypeScript for type safety and styled-components for flexible styling, this library provides a solid foundation for building modern web applications.",
                duration: "3 mois",
                team: "2 personnes",
                status: "Terminé",
                images: [{ url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800", caption: "Storybook interface showing component variations" }, { url: "https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=800", caption: "Component documentation with usage examples" }],
                techStack: ["Github","Power BI","Python"],
                features: ["20+ reusable components with consistent design patterns", "Full TypeScript support with comprehensive type definitions", "Flexible theming system using styled-components", "Interactive documentation with Storybook", "Comprehensive unit tests with high coverage", "Automated testing and deployment pipeline", "NPM package with proper versioning and changelogs", "Accessibility features built into all components"],
                challenges: "Creating a flexible theming system that could accommodate different design requirements while maintaining consistency was complex. I also had to ensure proper tree-shaking and bundle optimization for library consumers. Testing components in isolation while ensuring they work well together required careful planning of the testing strategy.",
                learnings: "This project taught me about library design patterns and the importance of API consistency. I gained deep knowledge of TypeScript's advanced features and learned about package publishing and versioning strategies. The experience also improved my understanding of accessibility principles and how to build inclusive user interfaces."
            },
            {
                id: 5,
                title: "Modèle de prédiction des retours de commande en ligne",
                type: "project",
                company: "ba&sh",
                startDate: "09/2023",
                endDate: "12/2023",
                description: "Développement d'un modèle de prédiction des retours de commandes en ligne",
                position: ["Data Scientist","Data Analyst"],
                category: ["Machine Learning","Analyse et Visualisation de données"],
                keywords: ["Python",'Jupyter notebook','Power BI','Scikit Learn'],
                tags: ["Python",'Jupyter notebook','Power BI'],
                github: "",
                demo: null,
                overview: "A robust RESTful API designed to power task management applications. Built with scalability and performance in mind, this API provides comprehensive task management capabilities with real-time features. The architecture follows REST principles while incorporating modern features like WebSocket connections for live updates.",
                duration: "3 mois",
                team: "4 personnes",
                status: "Terminé",
                images: [{ url: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800", caption: "API documentation and endpoint testing interface" }],
                techStack: ["Python",'Jupyter notebook','Power BI'],
                features: ["RESTful API design with proper HTTP methods and status codes", "User authentication and authorization with JWT tokens", "CRUD operations for tasks, projects, and user management", "File upload functionality for task attachments", "Real-time notifications using WebSocket connections", "Data validation and sanitization for security", "Rate limiting and request throttling", "Comprehensive error handling and logging"],
                challenges: "Implementing real-time features while maintaining API performance was challenging. I had to carefully design the WebSocket integration to avoid conflicts with REST endpoints. Another challenge was handling file uploads securely while managing storage efficiently. I solved these by implementing proper middleware chains and using cloud storage with signed URLs.",
                learnings: "This project deepened my understanding of API design principles and real-time communication patterns. I learned about the trade-offs between different authentication methods and gained experience with MongoDB's aggregation pipeline for complex queries. The project also taught me about API security best practices and performance optimization techniques."
            },
            {
                id: 6,
                title: "Modèle d'adaptive learning pour la personnalisation du parcours d'apprentissage utilisateur",
                type: "project",
                company: "TinyCoaching",
                startDate: "01/2023",
                endDate: "03/2023",
                description: "Développement d'un modèle d'adaptive learning pour la personnalisation du parcours d'apprentissage utilisateur",
                position: "Data Scientist",
                category: ["Machine Learning","Analyse et Visualisation de données"],
                keywords: ["Machine Learning", "Analyse et Visualisation de données", "Power BI", "Python", "dashboard"],
                tags: ["Machine Learning", "Analyse et Visualisation de données", "Power BI", "Python", "dashboard"],
                github: "https://github.com/yourusername/weather-dashboard",
                demo: "https://your-weather-app.com",
                overview: "An intuitive weather dashboard that provides comprehensive weather information with a focus on user experience and accessibility. The application combines current weather data with extended forecasts, featuring a clean interface that adapts to different screen sizes and user preferences.",
                duration: "3 mois",
                team: "4 personnes",
                status: "Terminé",
                images: [{ url: "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?w=800", caption: "Main dashboard showing current weather and forecasts" }, { url: "https://images.unsplash.com/photo-1592210454359-9043f067919b?w=800", caption: "Dark theme with detailed weather metrics" }],
                techStack: ["Python","Power BI","Github","Jupyter Notebook"],
                features: ["Automatic location detection using browser geolocation", "Search functionality for cities worldwide", "Current weather conditions with detailed metrics", "7-day weather forecast with hourly breakdowns", "Favorites system for quick access to saved locations", "Dark/light theme toggle with user preference persistence", "Responsive design optimized for all device sizes", "Weather data visualization with interactive charts"],
                challenges: "The biggest challenge was handling the various edge cases with the geolocation API and managing API rate limits efficiently. Weather data can be inconsistent, so I implemented robust error handling and fallback mechanisms. I also had to optimize the app for different network conditions and handle offline scenarios gracefully.",
                learnings: "This project improved my skills in working with external APIs and handling asynchronous data. I learned about browser APIs like Geolocation and gained experience in creating responsive designs that work well across different devices. The project also taught me about state management patterns in React and performance optimization techniques."
            },
            {
                id: 7,
                title: "Modèles d'annotation et de classification d'images pour les vides et les composants dans les circuits imprimés",
                type: "project",
                company: "Projet d'école",
                startDate: "11/2024",
                endDate: "11/2024",
                description: "Développement d'une interface permettant de segmenter les vides et composantes sur un circuit et de ré-entrainer un modèle de segmentation sur les images annotées",
                position: "Data Scientist",
                category: ["Deep Learning"],
                keywords: ["Deep Learning","Hugging Face"," Flask","Déploiement","Github"],
                tags: ["Deep Learning","Hugging Face"," Flask","Déploiement","Github"],
                github: "https://github.com/IThioye/final_project_sam_yolo",
                demo: "https://ibrahimathioye-sam-yolo-flask.hf.space/",
                overview: "An intuitive weather dashboard that provides comprehensive weather information with a focus on user experience and accessibility. The application combines current weather data with extended forecasts, featuring a clean interface that adapts to different screen sizes and user preferences.",
                duration: "1 mois",
                team: "4 personnes",
                status: "Terminé",
                images: [{ url: "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?w=800", caption: "Main dashboard showing current weather and forecasts" }, { url: "https://images.unsplash.com/photo-1592210454359-9043f067919b?w=800", caption: "Dark theme with detailed weather metrics" }],
                techStack: ["Python","Flask","Github","Hugging Face"],
                features: ["Automatic location detection using browser geolocation", "Search functionality for cities worldwide", "Current weather conditions with detailed metrics", "7-day weather forecast with hourly breakdowns", "Favorites system for quick access to saved locations", "Dark/light theme toggle with user preference persistence", "Responsive design optimized for all device sizes", "Weather data visualization with interactive charts"],
                challenges: "The biggest challenge was handling the various edge cases with the geolocation API and managing API rate limits efficiently. Weather data can be inconsistent, so I implemented robust error handling and fallback mechanisms. I also had to optimize the app for different network conditions and handle offline scenarios gracefully.",
                learnings: "This project improved my skills in working with external APIs and handling asynchronous data. I learned about browser APIs like Geolocation and gained experience in creating responsive designs that work well across different devices. The project also taught me about state management patterns in React and performance optimization techniques."
            },
            {
                id: 8,
                title: "Système multi-agents de connecteurs de concepts",
                type: "project",
                company: "Projet perso",
                startDate: "11/2025",
                endDate: "12/2025",
                description: "Système multi-agents permettant de comprendre le lien entre deux concepts de disciplines différentes",
                position: "Data Scientist",
                category: ["Deep Learning"],
                keywords: ["Deep Learning","Hugging Face"," Flask","Déploiement","Github","Agents IA"],
                tags: ["Deep Learning","Hugging Face"," Flask","Déploiement","Github"],
                github: "https://github.com/IThioye/Concept-Connector",
                demo: "",
                overview: "Un système d'IA multi-agents local qui découvre et explique les liens entre les concepts de différentes disciplines — construit avec Flask, Ollama et une interface légère utilisant HTML/CSS/JS.",
                duration: "2 mois",
                team: "Solo",
                status: "Terminé",
                images: [],
                techStack: ["Python","Flask","Github","Ollama"],
                features: ["Backend (Flask) utilisant un LLM open source", "7 agents travaillant de manière asynchronique avec chacun une tâche spécifique", "Personnalisation de la réponse selon le background utilisateur (niveau scolaire, système éducatif,etc.", "Détection de biais dans les réponses et métriques de fairness"],
                challenges: "Le plus gros problème résidait dans la maitrise de l'output du LLM, à savoir obtenir exactement une sortie JSON lorsque c'est demandé car la logique du système en dépend",
                learnings: "J'ai pu apprendre à développer un système d'agents IA en utilisant un modèle open source"
            }
        ];
        
const certifications = [
            {
                id: 1,
                title: "Microsoft Certified: Azure Data Scientist Associate",
                issuer: "Microsoft",
                date: "2025",
                link: "https://learn.microsoft.com/api/credentials/share/en-us/IbrahimaTHIOYE-2392/321034E6B5AA0D55?sharingId=571CABD87EB452E1"
            },
            {
                id: 2,
                title: "AI Product Engineering: From Concept to Market",
                issuer: "UC Berkeley",
                date: "2025",
                link: "https://badgr.com/public/assertions/kltf95JQQQWVjNzApdzw6w"
            }
        ];

export { projects, certifications };

